### ISSUE TITLE
Clarification regarding predict_mode argument

### ISSUE THREAD

**Issue by ericzhao28** [xiul-msr/e2e_dialog_challenge#9]
Hey, I was just wondering what the agent.predict_mode argument corresponded to. It appears that it is used to indicate (when True) that the dqn agent is in evaluation mode (in contrast to training). If that is the case, I was wondering why experience replay is disabled (outside of warm-starts) when predict_mode is False?
Thanks!

**Comment by xjli** [comment]
There is anther case, when the model is trained, it will be loaded for test only, in this case, predict_mode = False and warm_start=2, so no experience reply is added, because this is only for running test on trained model, no training here. So, no need experience reply. 

You can also enable the experience reply for the above case, but the cost is you need to maintain a large buffer. No training here, so disable the experience reply.

**Comment by ericzhao28** [comment]
Thanks for the clarification.
